version: '3'
services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - /home/ubuntu/docker_saas/mysql_data:/var/lib/mysql
      - ./mysql/privileges.sql:/docker-entrypoint-initdb.d/privileges.sql
      - /home/ubuntu/docker_saas/saas_init.sql:/docker-entrypoint-initdb.d/saas_init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo
      - MYSQL_USER=rootuser
      - MYSQL_PASSWORD=abc12345
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"

  

  web:
    build: .
    privileged: true
    restart: always
    volumes:
      - .:/code
      - /data:/data
      - ./supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./supervisor/gunicorn/gunicorn.conf:/etc/supervisor/conf.d/gunicorn.conf
      - ./supervisor/nginx/nginx.conf:/etc/supervisor/conf.d/nginx.conf
      - ./supervisor/celery/dmp_celery.conf:/etc/supervisor/conf.d/dmp_celery.conf
      - ./supervisor/celery/dmp_celery_beat.conf:/etc/supervisor/conf.d/dmp_celery_beat.conf
      - ./nginx/saas:/etc/nginx/sites-available/saas
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "8999:8000"
      - "80:80"
      - "443:443"
    links:
      - db
      - redis
     
